service: spajam2019-get-twitter

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: ${opt:region, self:custom.defaultRegion}

custom:
  defaultStage: dev
  defaultProfile: default
  defaultRegion: ap-northeast-1

functions:
  getTwitettr:
    handler: handler.index
    environment:
      REGION: ${self:provider.region}
      CONSUMERKEY: ${opt:consumerKey}
      CONSUMERSECRET: ${opt:consumerSecret}
      ACCESSTOKEN: ${opt:accessToken}
      ACCESSTOKENSECRET: ${opt:accessTokenSecret}
    events:
      - http:
          path: tag/{proxy+}
          method: any
          cors: true
