service: spajam2019-create-s3-bucket

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: ${opt:region, self:custom.defaultRegion}

custom:
  defaultStage: dev
  defaultProfile: default
  defaultRegion: ap-northeast-1

resources:
 Resources:
   NewResource:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${opt:bucket}
